version: "3.0"

services:
    app1:
        build: 
            dockerfile: ./dockerfile.nodeApp
            context: .
        environment:
            APPID: "2222"
        ports:
            - 2222:9999
        image: "node/app1"
        container_name: app1
    app2:
        build: 
            dockerfile: ./dockerfile.nodeApp
            context: .
        environment:
            APPID: "3333"
        ports:
            - 3333:9999
        image: "node/app2"
        container_name: app2
    app3:
        build: 
            dockerfile: ./dockerfile.nodeApp
            context: .
        environment:
            APPID: "4444"
        ports:
            - 4444:9999
        image: "node/app3"
        container_name: app3
    nginx:
        image: nginx:latest
        ports: 
            - 8000:8080
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - "app1"
            - "app2"
            - "app3"